# coding: utf-8
"""
浦东大屏
"""
from sqlalchemy import Column, DECIMAL, Date, DateTime, Float, Index, JSON, LargeBinary, String, TIMESTAMP, Table, text
from sqlalchemy.dialects.mysql import CHAR, INTEGER, LONGBLOB, LONGTEXT, TEXT, TINYTEXT, VARCHAR

from sqlalchemylib.sqlalchemylib.connection import Base


class AttentionOrder(Base):
	__tablename__ = 'attention_order'
	__table_args__ = (
		Index('attention_order_unique', 'taskid', 'userId', unique=True),
		{'comment': '关注工单'}
	)

	taskid = Column(VARCHAR(50))
	status = Column(INTEGER(11))
	login_name = Column(VARCHAR(50))
	source = Column(VARCHAR(20))
	id = Column(INTEGER(11), primary_key=True)
	create_time = Column(TIMESTAMP)
	source_user = Column(VARCHAR(50))
	update_time = Column(TIMESTAMP, comment='修改时间')
	status_accept = Column(INTEGER(11), server_default=text("'0'"), comment='0：未受理 。1：已受理')
	remark = Column(TEXT, comment='备注')
	userId = Column(INTEGER(11), comment='用户id')
	organId = Column(INTEGER(11), comment='部门id')
	monitor_step = Column(INTEGER(11), comment='0-了解情况；1-监督检查；2-移送线索')
	handle_result = Column(String(255), comment='处置结果')
	order_source = Column(String(255), comment='工单来源')
	receiver = Column(String(255), comment='接收人')
	send_msg = Column(INTEGER(11), server_default=text("'0'"), comment='是否发送短信:0-否;1-是')
	org_name = Column(String(255), comment='部门名称')
	from_area = Column(VARCHAR(1), server_default=text("'0'"), comment='是否是区级了解情况推过来的：0-否，1-是')


class Datum(Base):
	__tablename__ = 'data'
	__table_args__ = (
		Index('pudong_data_index', 'createtime', 'endtime'),
	)

	accepttime = Column(TIMESTAMP, comment='接单时间（最后一次主责部门处理完成时间）')
	address = Column(VARCHAR(1000), comment='发生地址')
	allendtime = Column(TIMESTAMP, comment='整体案卷截止时间（红灯开始时间）')
	allimportanttime = Column(TIMESTAMP, comment='整体案卷橙灯开始时间（根据紧急程度important计算的）')
	alllight = Column(VARCHAR(20), index=True, comment='整体超时')
	allmanyi = Column(INTEGER(11), comment='回访总体满意度(结案后回访)')
	allmanyiname = Column(VARCHAR(50), comment='总体满意度(结案后回访)')
	allmiddletime = Column(TIMESTAMP, comment='整体案卷黄灯开始时间（根据紧急程度middle计算的）')
	appeal_explain = Column(VARCHAR(500), comment='诉求认定说明（区反馈市）')
	appealtype = Column(VARCHAR(100), comment='诉求认定（区反馈市）')
	appealtypecode = Column(VARCHAR(100), comment='诉求认定编码（区反馈市）')
	approach = Column(INTEGER(11), comment='12345工单处理方式/案卷类型（0：转办;1：督办;2：回访复核）')
	backcount = Column(INTEGER(11), comment='退单次数')
	backtocitynote = Column(VARCHAR(500), comment='退回市级备注')
	badging_unit = Column(VARCHAR(100), comment='落款单位')
	banliresult = Column(INTEGER(11), comment='办理结果')
	banliresult_12345 = Column(INTEGER(11), comment='12345案件反馈给市办理结果 (0:解决，1:未解决，2:部分解决，3:不办理退单)')
	callback_flag = Column(INTEGER(11), comment='12345回访复核单状态标识(0：否，1：是)')
	callnumber = Column(VARCHAR(20), comment='来电号码')
	cancelnote = Column(VARCHAR(300), comment='作废备注')
	cancletime = Column(TIMESTAMP, comment='作废时间')
	caseendbccode = Column(VARCHAR(20), comment='统计大类')
	caseendbcname = Column(VARCHAR(50), comment='统计大类名称')
	caseendsccode = Column(VARCHAR(20), comment='统计小类')
	caseendscname = Column(VARCHAR(50), comment='统计小类名称')
	caseend = Column(INTEGER(11), comment='是否自行处置')
	caseendnote = Column(VARCHAR(300), comment='结案意见')
	casesn = Column(VARCHAR(100), comment='案卷编号')
	casevaluation = Column(INTEGER(11), comment='结案评价')
	casevaluation_12345 = Column(INTEGER(11), comment='结案评判（12345案件反馈给市）')
	casevaluationname = Column(VARCHAR(100), comment='结案评判名称')
	checkimage = Column(VARCHAR(4000), comment='核查图片')
	checkresult = Column(INTEGER(11), comment='最后的核查结果 （1:完成，0:未完成）')
	checkwav = Column(VARCHAR(2000), comment='核查声音')
	communitycode = Column(VARCHAR(8), comment='村、居村编码')
	communityname = Column(VARCHAR(50), comment='居村委名')
	contactinfo = Column(VARCHAR(100), comment='联系方式')
	contactmode = Column(VARCHAR(50), comment='反映人联系方式')
	coordx = Column(Float(asdecimal=True), comment='X坐标')
	coordy = Column(Float(asdecimal=True), comment='Y坐标')
	createtime = Column(TIMESTAMP, index=True, comment='立案时间（最后一次立案时间）')
	deptcode = Column(VARCHAR(20), comment='立案部门')
	deptname = Column(VARCHAR(100), comment='立案部门名称')
	description = Column(VARCHAR(2000), index=True, comment='问题描述')
	description_12345 = Column(VARCHAR(1000), comment='反馈结论（12345案件反馈给市）')
	discovertime = Column(TIMESTAMP, comment='发现时间')
	dispatchnote = Column(VARCHAR(2000), comment='派遣备注（最后主责派遣时间）')
	dispatchtime = Column(TIMESTAMP, comment='派遣时间（最后主责派遣时间）')
	du_limit = Column(VARCHAR(10), comment='12345督办时限(天)')
	endnote = Column(VARCHAR(2000), comment='结案备注')
	endresult = Column(INTEGER(11), comment='结案评价')
	endresultnew = Column(VARCHAR(1000), comment='结案意见')
	endtime = Column(TIMESTAMP, index=True, comment='结案时间')
	executedeptcode = Column(VARCHAR(20), comment='最后一次主责部门')
	executedeptname = Column(VARCHAR(100), comment='最后责任主责名')
	facilitytype = Column(INTEGER(11), comment='责任归属（最后主责）')
	fact_explain = Column(VARCHAR(500), comment='事实认定说明(区反馈市)')
	facttype = Column(VARCHAR(100), comment='事实认定（区反馈市）')
	facttypecode = Column(VARCHAR(100), comment='事实认定编码（区反馈市）')
	feedbacktime_12345 = Column(TIMESTAMP, comment='反馈时间（区反馈市）')
	first_contact = Column(VARCHAR(20), comment='是否联系')
	firsthanddeptcode = Column(VARCHAR(50), comment='原始归属部门编号')
	firsthanddeptname = Column(VARCHAR(100), comment='原始归属部门名称')
	gridcode = Column(VARCHAR(8), comment='万米网格编码')
	hashotlinereminders = Column(INTEGER(11), comment='市催办(1:是，0：否）')
	haslead = Column(VARCHAR(50), index=True, comment='领导督办(1:是，0：否）')
	hasleadtypecount = Column(INTEGER(11), comment='领导督办次数')
	hastentype = Column(VARCHAR(50), comment='是否催办(1:是，0：否）')
	hastentypecount = Column(INTEGER(11), comment='催办过的次数')
	hecha = Column(VARCHAR(50), comment='核查')
	hechakeepername = Column(VARCHAR(100), comment='核查监督员名')
	hechakeepersn = Column(VARCHAR(20), comment='核查监督员编号（最后一次核查监督员编号）')
	heshi = Column(VARCHAR(50), comment='核实')
	heshikeepersn = Column(VARCHAR(20), comment='核实监督员编号（最后一次核实监督员编号）')
	hotlinesn = Column(VARCHAR(100), comment='外系统管理单号')
	id = Column(INTEGER(11), comment='序列号')
	imagefilename = Column(TEXT, comment='上报图片')
	importantsolvingtime = Column(TIMESTAMP, comment='处理阶段橙灯开始时间')
	inertview = Column(VARCHAR(2000), comment='回访意见')
	infoatcode = Column(VARCHAR(20), comment='问题管理要点编码')
	infoatname = Column(TEXT, comment='管理要点')
	infobccode = Column(VARCHAR(2), comment='问题大类编号')
	infobcname = Column(VARCHAR(50), comment='案件大类名')
	infosccode = Column(VARCHAR(2), comment='问题小类编号')
	infoscname = Column(VARCHAR(50), comment='案件小类名')
	infosourceid = Column(INTEGER(11), comment='问题来源')
	infosourcename = Column(VARCHAR(200), comment='问题来源名称')
	infotypeid = Column(INTEGER(11), comment='案件属性编码(0:部件；1：事件；...)')
	infotypename = Column(TEXT, comment='案件属性名')
	infozccode = Column(VARCHAR(2), comment='问题子类编码')
	infozcname = Column(TEXT, comment='案件子类名')
	insertdeptcode = Column(TEXT, comment='收集部门')
	insertdeptname = Column(TEXT, comment='收集部门名')
	is_public = Column(TEXT, comment='是否公开（1：是，0：否）')
	isanonymity = Column(INTEGER(11), comment='是否匿名（1：是，0：否）')
	isfast = Column(TEXT, comment='快速上报（1：快速上报，0或空：非快速上报）')
	isfeedbak = Column(INTEGER(11), comment='12345是否提前反馈（1：是，0：否）')
	isfirstcontact = Column(INTEGER(11), comment='是否现行联系')
	isfirstcontactname = Column(TEXT, comment='是否先行联系中文名')
	isreply = Column(VARCHAR(20), comment='是否答复')
	issolving = Column(INTEGER(11), comment='回访环节填写是否完成(0:完成;1:未完成;2:无法回访)')
	issolvingname = Column(TEXT, comment='回访结果')
	isstandard = Column(TEXT, comment='1 : 市级标准    0:非市级标准')
	isstubborn = Column(TEXT, comment='疑难案件（1：是，0：否）')
	istypical = Column(TEXT, comment='典型案件（1：是，0：否）')
	keepersn = Column(TEXT, comment='上报监督员编号')
	lastsolvingtime = Column(TIMESTAMP, comment='处理阶段红灯开始时间（处理截止时间）')
	middlesolvingtime = Column(TIMESTAMP, comment='处理阶段黄灯开始时间')
	not_reason = Column(TEXT, comment='未联原因')
	partsn = Column(TEXT, comment='部件编号')
	pexecutedeptcode_mh = Column(TEXT, comment='二级主责部门(新)')
	pexecutedeptname_mh = Column(TEXT, comment='二级主责部门名(新)')
	qpdispatchtime = Column(TIMESTAMP, comment='区下派最后主责派遣时间')
	qpexecutedeptcode = Column(TEXT, comment='浦东区平台视角派遣的最后一次主责部门编号')
	qpexecutedeptname = Column(TEXT, comment='浦东区平台视角派遣的最后一次主责部门名称')
	qplastsolvingtime = Column(TIMESTAMP, comment='区派遣处置截止时限')
	qpsolvingtime = Column(TIMESTAMP, comment='区下派最后主责处理完成时间')
	replayform = Column(TEXT, comment='回复形式（区反馈市）')
	replayformname = Column(TEXT, comment='回复形式名（区反馈市）')
	reply_point = Column(TEXT, comment='答复要点（区反馈市）')
	reply_time = Column(DateTime, comment='答复时间（区反馈市）')
	reply_type = Column(TEXT, comment='答复方式（区反馈市）')
	reportdept = Column(INTEGER(11), comment='渠道来源')
	reportdeptname = Column(TEXT, comment='渠道来源名')
	reporter = Column(TEXT, comment='反映人')
	result_12345 = Column(TEXT, comment='12345反馈结论(区反馈市)')
	resulttype = Column(INTEGER(11), comment='完成情况')
	resulttypename = Column(TEXT, comment='完成情况')
	satisfied = Column(TEXT, comment='12345是否满意（区反馈市）')
	satisfied_explain = Column(TEXT, comment='市民反馈说明（区反馈市）')
	servicetype = Column(TEXT, comment='业务类型')
	servicetypename = Column(VARCHAR(20), comment='业务类型名')
	shangbaohechatime = Column(TIMESTAMP, comment='上报核查时间（最后一次上报核查时间）')
	shangbaoheshitime = Column(TIMESTAMP, comment='上报核实时间（最后一次上报核实时间）')
	similarcasesn = Column(TEXT, comment='相关案件编号')
	solvinglight = Column(TEXT, comment='处理超时')
	solvingnote = Column(TEXT, comment='处理备注')
	solvingresult = Column(TEXT, comment='处理结果')
	solvingresultinfo = Column(TEXT, comment='处理结果名')
	solvingtime = Column(TIMESTAMP, comment='处理完成时间（最后一次主责部门处理完成时间）')
	speicalsign = Column(TEXT, index=True, comment='案件特殊标识（特征要素）')
	status = Column(INTEGER(11), comment='案件状态')
	statusname = Column(TEXT, comment='案件状态名称')
	streetcode = Column(VARCHAR(4), comment='街道编号')
	streetname = Column(TEXT, comment='街道名')
	subexecutedeptcode_mh = Column(TEXT, comment='三级主责部门编码')
	subexecutedeptname_mh = Column(TEXT, comment='三级主责部门名称')
	supervisedate = Column(TIMESTAMP, comment='申请督办日期')
	supervisetime = Column(TIMESTAMP, comment='申请督办时间（最后一次申请督办时间）')
	synctime = Column(TIMESTAMP, comment='最新同步时间')
	taskid = Column(VARCHAR(20), unique=True, comment='任务编号')
	telasktime = Column(TIMESTAMP, comment='回访时间（最后一次回访时间）')
	telasktype = Column(INTEGER(11), comment='回访环节填写的回访方式（0：监督员核查，1：电话回访，2：先核查后回访）')
	tentypedate = Column(TIMESTAMP, comment='催办日期')
	tentypenote = Column(TEXT, comment='催办批注')
	upkeepername = Column(TEXT, comment='监督员名')
	urge_count = Column(INTEGER(11), comment='12345催单次数（12345催单时带过来的催单次数）')
	urgentdegree = Column(INTEGER(11), index=True, comment='紧急程度（0：一般；1：紧急）')
	userevaluate = Column(INTEGER(11), comment='用户评价满意度(0:满意;1:基本满意;2:不满意)')
	userevaluatename = Column(TEXT, comment='用户评价满意度中文名')
	verifyresult = Column(INTEGER(11), comment='最后的核实结果 （1:属实，0:不属实）')
	viewinfo = Column(TEXT, comment='现场查看')
	wavfilename = Column(TEXT, comment='上报声音')
	workgridcode = Column(VARCHAR(6), comment='责任网格')
	wp_source = Column(TEXT, comment='12345工单来源')
	wp_type = Column(TEXT, comment='12345业务类型')
	xiafahechatime = Column(TIMESTAMP, comment='下发核查时间（最后一次下发核查时间）')
	xiafaheshitime = Column(TIMESTAMP, comment='下发核实时间（最后一次下发核实时间）')
	participant = Column(TEXT, comment='所属行业')
	smartdesc = Column(TEXT, comment='智能分析说明')
	ssid = Column(INTEGER(11), comment='二级部门转派编号')
	fsid = Column(INTEGER(11), comment='区派遣编号')
	csid = Column(INTEGER(11), comment='立案部门派遣编号')
	smarttype = Column(INTEGER(11), comment='智能分析类型（1：视频识别 2：数据分析 3：物联感知）')
	inserttime = Column(TIMESTAMP, comment='推送时间')
	dt_createdtime = Column(TIMESTAMP, comment='中台系统创建时间')
	lb_createduser = Column(VARCHAR(20), comment='中台系统创建者')
	dt_updatedtime = Column(TIMESTAMP, comment='中台系统更新时间')
	lb_updateduser = Column(TEXT, comment='中台系统更新者')
	isredispatch = Column(INTEGER(11), comment='二次交办')
	partition_by_ymd_column = Column(TEXT)
	stime = Column(TEXT)
	firstdispatchtime = Column(TEXT)
	pid = Column(INTEGER(11), primary_key=True)
	dissatisfied_type = Column(CHAR(1), index=True)
	dissatisfied_date = Column(TIMESTAMP, index=True)


class DictImportantType(Base):
	__tablename__ = 'dict_important_type'
	__table_args__ = {'comment': '重点工单条件配置表'}

	id = Column(INTEGER(11), primary_key=True)
	dept_type = Column(VARCHAR(20), comment='开启部门类型 1城运 2纪委')
	type_name = Column(VARCHAR(200), comment='类型名称')
	type_condition = Column(VARCHAR(2000), comment='查询条件')
	is_enable = Column(VARCHAR(1), comment='是否启用')
	serial_no = Column(INTEGER(11), comment='序号')


class Segment(Base):
	__tablename__ = 'segment'
	__table_args__ = (
		Index('segment_diff', 'taskid', 'word', unique=True),
	)

	id = Column(INTEGER(11), primary_key=True)
	taskid = Column(VARCHAR(100))
	word = Column(VARCHAR(50))
	createtime = Column(DateTime, index=True)
